set module xddr_cdc
create_ip -vlnv xilinx.com:ip:axi_interconnect:1.7 -module $module
set_property -dict [list \
                    CONFIG.ACLK_PERIOD  {0}\
                    CONFIG.AXI4_MASTER_M00_AXI.INSERT_VIP {0}\
                    CONFIG.AXI4_SLAVE_S00_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S01_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S02_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S03_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S04_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S05_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S06_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S07_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S08_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S09_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S10_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S11_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S12_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S13_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S14_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI4_SLAVE_S15_AXI.INSERT_VIP  {0}\
                    CONFIG.AXI_ADDR_WIDTH {40}\
                    CONFIG.Component_Name {axi_interconnect_0}\
                    CONFIG.INTERCONNECT_CLK.INSERT_VIP {0}\
                    CONFIG.INTERCONNECT_DATA_WIDTH  {512}\
                    CONFIG.INTERCONNECT_RST.INSERT_VIP  {0}\
                    CONFIG.M00_AXI_ACLK_RATIO {1:1}\
                    CONFIG.M00_AXI_DATA_WIDTH {512}\
                    CONFIG.M00_AXI_IS_ACLK_ASYNC  {1}\
                    CONFIG.M00_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.M00_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.M00_AXI_READ_ISSUING {1}\
                    CONFIG.M00_AXI_REGISTER {0}\
                    CONFIG.M00_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.M00_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.M00_AXI_WRITE_ISSUING  {1}\
                    CONFIG.M00_CLK.INSERT_VIP {0}\
                    CONFIG.NUM_SLAVE_PORTS  {1}\
                    CONFIG.S00_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S00_AXI_ARB_PRIORITY {0}\
                    CONFIG.S00_AXI_DATA_WIDTH {512}\
                    CONFIG.S00_AXI_IS_ACLK_ASYNC  {1}\
                    CONFIG.S00_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S00_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S00_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S00_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S00_AXI_REGISTER {0}\
                    CONFIG.S00_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S00_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S00_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S00_CLK.INSERT_VIP {0}\
                    CONFIG.S01_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S01_AXI_ARB_PRIORITY {0}\
                    CONFIG.S01_AXI_DATA_WIDTH {32}\
                    CONFIG.S01_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S01_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S01_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S01_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S01_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S01_AXI_REGISTER {0}\
                    CONFIG.S01_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S01_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S01_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S01_CLK.INSERT_VIP {0}\
                    CONFIG.S02_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S02_AXI_ARB_PRIORITY {0}\
                    CONFIG.S02_AXI_DATA_WIDTH {32}\
                    CONFIG.S02_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S02_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S02_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S02_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S02_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S02_AXI_REGISTER {0}\
                    CONFIG.S02_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S02_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S02_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S02_CLK.INSERT_VIP {0}\
                    CONFIG.S03_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S03_AXI_ARB_PRIORITY {0}\
                    CONFIG.S03_AXI_DATA_WIDTH {32}\
                    CONFIG.S03_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S03_AXI_READ_ACCEPTANCE {1}\
                    CONFIG.S03_AXI_READ_FIFO_DELAY {0}\
                    CONFIG.S03_AXI_READ_FIFO_DEPTH {0}\
                    CONFIG.S03_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S03_AXI_REGISTER {0}\
                    CONFIG.S03_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S03_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S03_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S03_CLK.INSERT_VIP {0}\
                    CONFIG.S04_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S04_AXI_ARB_PRIORITY {0}\
                    CONFIG.S04_AXI_DATA_WIDTH {32}\
                    CONFIG.S04_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S04_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S04_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S04_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S04_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S04_AXI_REGISTER {0}\
                    CONFIG.S04_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S04_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S04_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S04_CLK.INSERT_VIP {0}\
                    CONFIG.S05_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S05_AXI_ARB_PRIORITY {0}\
                    CONFIG.S05_AXI_DATA_WIDTH {32}\
                    CONFIG.S05_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S05_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S05_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S05_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S05_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S05_AXI_REGISTER {0}\
                    CONFIG.S05_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S05_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S05_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S05_CLK.INSERT_VIP {0}\
                    CONFIG.S06_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S06_AXI_ARB_PRIORITY {0}\
                    CONFIG.S06_AXI_DATA_WIDTH {32}\
                    CONFIG.S06_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S06_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S06_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S06_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S06_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S06_AXI_REGISTER {0}\
                    CONFIG.S06_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S06_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S06_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S06_CLK.INSERT_VIP {0}\
                    CONFIG.S07_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S07_AXI_ARB_PRIORITY {0}\
                    CONFIG.S07_AXI_DATA_WIDTH {32}\
                    CONFIG.S07_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S07_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S07_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S07_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S07_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S07_AXI_REGISTER {0}\
                    CONFIG.S07_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S07_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S07_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S07_CLK.INSERT_VIP {0}\
                    CONFIG.S08_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S08_AXI_ARB_PRIORITY {0}\
                    CONFIG.S08_AXI_DATA_WIDTH {32}\
                    CONFIG.S08_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S08_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S08_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S08_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S08_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S08_AXI_REGISTER {0}\
                    CONFIG.S08_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S08_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S08_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S08_CLK.INSERT_VIP {0}\
                    CONFIG.S09_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S09_AXI_ARB_PRIORITY {0}\
                    CONFIG.S09_AXI_DATA_WIDTH {32}\
                    CONFIG.S09_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S09_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S09_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S09_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S09_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S09_AXI_REGISTER {0}\
                    CONFIG.S09_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S09_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S09_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S09_CLK.INSERT_VIP {0}\
                    CONFIG.S10_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S10_AXI_ARB_PRIORITY {0}\
                    CONFIG.S10_AXI_DATA_WIDTH {32}\
                    CONFIG.S10_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S10_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S10_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S10_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S10_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S10_AXI_REGISTER {0}\
                    CONFIG.S10_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S10_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S10_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S10_CLK.INSERT_VIP {0}\
                    CONFIG.S11_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S11_AXI_ARB_PRIORITY {0}\
                    CONFIG.S11_AXI_DATA_WIDTH {32}\
                    CONFIG.S11_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S11_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S11_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S11_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S11_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S11_AXI_REGISTER {0}\
                    CONFIG.S11_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S11_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S11_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S11_CLK.INSERT_VIP {0}\
                    CONFIG.S12_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S12_AXI_ARB_PRIORITY {0}\
                    CONFIG.S12_AXI_DATA_WIDTH {32}\
                    CONFIG.S12_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S12_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S12_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S12_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S12_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S12_AXI_REGISTER {0}\
                    CONFIG.S12_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S12_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S12_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S12_CLK.INSERT_VIP {0}\
                    CONFIG.S13_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S13_AXI_ARB_PRIORITY {0}\
                    CONFIG.S13_AXI_DATA_WIDTH {32}\
                    CONFIG.S13_AXI_IS_ACLK_ASYNC {0}\
                    CONFIG.S13_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S13_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S13_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S13_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S13_AXI_REGISTER {0}\
                    CONFIG.S13_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S13_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S13_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S13_CLK.INSERT_VIP {0}\
                    CONFIG.S14_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S14_AXI_ARB_PRIORITY {0}\
                    CONFIG.S14_AXI_DATA_WIDTH {32}\
                    CONFIG.S14_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S14_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S14_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S14_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S14_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S14_AXI_REGISTER {0}\
                    CONFIG.S14_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S14_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S14_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S14_CLK.INSERT_VIP {0}\
                    CONFIG.S15_AXI_ACLK_RATIO {1:1}\
                    CONFIG.S15_AXI_ARB_PRIORITY {0}\
                    CONFIG.S15_AXI_DATA_WIDTH {32}\
                    CONFIG.S15_AXI_IS_ACLK_ASYNC  {0}\
                    CONFIG.S15_AXI_READ_ACCEPTANCE  {1}\
                    CONFIG.S15_AXI_READ_FIFO_DELAY  {0}\
                    CONFIG.S15_AXI_READ_FIFO_DEPTH  {0}\
                    CONFIG.S15_AXI_READ_WRITE_SUPPORT {READ/WRITE}\
                    CONFIG.S15_AXI_REGISTER {0}\
                    CONFIG.S15_AXI_WRITE_ACCEPTANCE {1}\
                    CONFIG.S15_AXI_WRITE_FIFO_DELAY {0}\
                    CONFIG.S15_AXI_WRITE_FIFO_DEPTH {0}\
                    CONFIG.S15_CLK.INSERT_VIP {0}\
                    CONFIG.SYNCHRONIZATION_STAGES {3}\
                    CONFIG.THREAD_ID_WIDTH  {8}\
                   ]  [get_ips $module]
