##################################################################
# CREATE IP ila_generic
##################################################################

set ila ila_generic
create_ip -vlnv xilinx.com:ip:ila:6.2 -module ila_generic
set_property -dict { 
  CONFIG.C_PROBE17_WIDTH {64}
  CONFIG.C_PROBE16_WIDTH {64}
  CONFIG.C_PROBE15_WIDTH {64}
  CONFIG.C_PROBE14_WIDTH {64}
  CONFIG.C_PROBE13_WIDTH {64}
  CONFIG.C_PROBE12_WIDTH {64}
  CONFIG.C_PROBE11_WIDTH {64}
  CONFIG.C_PROBE10_WIDTH {64}
  CONFIG.C_PROBE9_WIDTH {64}
  CONFIG.C_PROBE8_WIDTH {64}
  CONFIG.C_PROBE7_WIDTH {64}
  CONFIG.C_PROBE6_WIDTH {64}
  CONFIG.C_PROBE5_WIDTH {64}
  CONFIG.C_PROBE4_WIDTH {64}
  CONFIG.C_PROBE3_WIDTH {64}
  CONFIG.C_PROBE2_WIDTH {64}
  CONFIG.C_PROBE1_WIDTH {64}
  CONFIG.C_PROBE0_WIDTH {64}
  CONFIG.C_DATA_DEPTH {4096}
  CONFIG.C_NUM_OF_PROBES {30}
  CONFIG.C_PROBE29_MU_CNT {16}
  CONFIG.C_PROBE28_MU_CNT {16}
  CONFIG.C_PROBE27_MU_CNT {16}
  CONFIG.C_PROBE26_MU_CNT {16}
  CONFIG.C_PROBE25_MU_CNT {16}
  CONFIG.C_PROBE24_MU_CNT {16}
  CONFIG.C_PROBE23_MU_CNT {16}
  CONFIG.C_PROBE22_MU_CNT {16}
  CONFIG.C_PROBE21_MU_CNT {16}
  CONFIG.C_PROBE20_MU_CNT {16}
  CONFIG.C_PROBE19_MU_CNT {16}
  CONFIG.C_PROBE18_MU_CNT {16}
  CONFIG.C_PROBE17_MU_CNT {16}
  CONFIG.C_PROBE16_MU_CNT {16}
  CONFIG.C_PROBE15_MU_CNT {16}
  CONFIG.C_PROBE14_MU_CNT {16}
  CONFIG.C_PROBE13_MU_CNT {16}
  CONFIG.C_PROBE12_MU_CNT {16}
  CONFIG.C_PROBE11_MU_CNT {16}
  CONFIG.C_PROBE10_MU_CNT {16}
  CONFIG.C_PROBE9_MU_CNT {16}
  CONFIG.C_PROBE8_MU_CNT {16}
  CONFIG.C_PROBE7_MU_CNT {16}
  CONFIG.C_PROBE6_MU_CNT {16}
  CONFIG.C_PROBE5_MU_CNT {16}
  CONFIG.C_PROBE4_MU_CNT {16}
  CONFIG.C_PROBE3_MU_CNT {16}
  CONFIG.C_PROBE2_MU_CNT {16}
  CONFIG.C_PROBE1_MU_CNT {16}
  CONFIG.C_PROBE0_MU_CNT {16}
  CONFIG.ALL_PROBE_SAME_MU_CNT {16}
} [get_ips ila_generic]

##################################################################

