../lib/clock/icg.sv
../lib/clock/icg_async.sv
../lib/clock/icg_rstn.sv
../lib/sync/sync.sv
../lib/sd_ppln.sv
../lib/sd_serdes.sv
../lib/sd_sync_fifo.sv
../lib/sd_hold_valid.sv

../lib/ot_ip/misc/sd_input_rstn.v
../lib/ot_ip/misc/sd_output_rstn.v
../lib/ot_ip/misc/sd_ppln_cell_rstn.v
../lib/ot_ip/misc/sd_ppln_delay_rstn.v
../lib/ot_ip/misc/ot_4to1_mux_with_buf_rstn.v
../lib/ot_ip/misc/ot_mux_with_buf_rstn.v
../lib/ot_ip/misc/ot_one_hot_to_idx.v
../lib/ot_ip/arbiter/ot_rr_arbiter_rstn.v
../lib/ot_ip/arbiter/ot_rr_arbiter_with_hold_rstn.v
../lib/ot_ip/fifo/sd_flop_fifo_rstn.v
../lib/flop_sram.sv

../lib/flatten_array.sv

../vcore_gen2/rtl/vcore_ppln.sv
../vcore_gen2/rtl/vcore_ppln_dec_disp.sv
../vcore_gen2/rtl/vcore_ppln_disp_exe.sv
../../rtl/lib/ot_ip/barrel/ot_barrel_shift_left.v
../../rtl/lib/ot_ip/barrel/ot_barrel_shift_right.v
../../rtl/lib/sdlib/rtl/verilog/forks/sd_mirror_atomic.v
../../rtl/lib/ot_ip/misc/sd_ppln_cell.v
../../rtl/lib/ot_ip/fifo/sd_flop_fifo.v
../../rtl/lib/sdlib/rtl/verilog/closure/sd_input.v
../../rtl/lib/sdlib/rtl/verilog/closure/sd_output.v
../../rtl/lib/ot_ip/misc/sd_id_pool.v
../../rtl/lib/ot_ip/memory/ot_flop_mem_1r1w.v
../../rtl/lib/ot_ip/fifo/ot_flop_fifo.v

../lib/ours_ip/ours_rob.sv
../lib/ours_ip/ours_fifo.sv
../lib/ours_ip/ours_vld_rdy_buf.sv
../lib/ours_ip/ours_one_hot_rr_arb.sv
../lib/ours_ip/ours_vld_rdy_rr_arb.sv
../lib/ours_ip/ours_vld_rdy_rr_arb_buf.sv
../lib/ours_ip/ours_multi_lyr_vld_rdy_rr_arb.sv
../lib/ours_ip/ours_vld_rdy_delay_line.sv
../lib/ours_ip/ours_axi4_aw_w_rr_arb_buf.sv
../lib/ours_ip/ours_axi4_r_rr_arb_buf.sv
../lib/ours_ip/ours_multi_lyr_axi4_aw_w_rr_arb.sv
../lib/ours_ip/ours_multi_lyr_axi4_r_rr_arb.sv
../lib/ours_ip/ours_conv_oursring_64_to_32.sv
../lib/ours_ip/ours_input_ppln.sv
../lib/ours_ip/ours_output_ppln.sv
../lib/ours_ip/ours_ppln_cell.sv

../lib/clock/glitch_free_clk_switch.sv
../lib/clock/glitch_free_clk_switch_rstn.sv
../lib/clock/pll.sv
../lib/clock/clk_div.sv
../lib/clock/clk_div_pwr2.sv
../lib/clock/clk_div_cfg.sv
../lib/clock/clk_div_fix.sv

../lib/top_cell/inv.sv
../lib/top_cell/or_gate.sv
../lib/top_cell/buf.sv
../lib/top_cell/clk_buf.sv
../lib/top_cell/chip_idle_gen.sv
../lib/top_cell/mux_Nto1_1bit.sv
../lib/dft_cell.sv

../lib/ours_bdg_x2p/ours_bdg_x2p_pkg.sv
../lib/ours_bdg_x2p/ours_bdg_x2p_cvt.sv
../lib/ours_bdg_x2p/ours_bdg_x2p_fifo.sv
../lib/ours_bdg_x2p/ours_bdg_x2p_pdec.sv
../lib/ours_bdg_x2p/ours_bdg_x2p.sv
../lib/ours_xm_to_cpu_noc/ours_xm_to_cpu_noc.sv
../lib/ours_xm_to_jtag/ours_xm_to_jtag.sv
../lib/ours_xm_to_jtag/ours_xm_to_jtag_req_proc.sv
../lib/ours_xm_to_jtag/ours_xm_to_jtag_shift_inst_data.sv
../lib/ours_xm_to_test_io/ours_xm_to_test_io.sv
../lib/ours_xm_to_test_io/ours_xm_to_test_io_req_proc.sv
../lib/ours_xm_to_test_io/ours_xm_to_test_io_shift_inst_data.sv
