
+define+PYGMY_ES1Y+FPGA+STATION_VP_PKG__SV+USE_POWER_PINS
/work/home/yinguohua/Downloads/AMD/orv64/rtl/common/pygmy_define.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/common/pygmy_cfg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/common/pygmy_typedef.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/common/pygmy_func.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/png-32/rtl/orv/orv_cfg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/png-32/rtl/orv/orv_typedef.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/png-32/rtl/orv/orv_func.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/plic/plic_typedef.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_param_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_typedef_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_func_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/vcore_gen2/rtl/vcore_cfg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/vcore_gen2/rtl/vcore_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/common/oursring_typedef.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/pygmy_intf_typedef.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_csr_mmu_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_dc_ma_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_ex_dc_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_tlb_flush_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/oursring_req_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/pcie_req_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/usb_cache_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/vpfp_chkr_csr_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_dma.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/mem_bar_status_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/pcie_resp_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/spi_m_req_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_dt.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/l2_ctrl_cfg_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/mem_bar_clear_banks_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/spi_s_rsp_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_ddr_top.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_if_ic_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_usb_top.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/dma_intr_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/dma_data_avail_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/scan_f_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/dtm_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/tcm_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_orv32.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_slow_io.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/mem_bar_status_banks_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/vpfp_chkr_vrf_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_pll.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/apb_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_vp.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/jtag_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_cache_tlb_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/vpfp_chkr_irf_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/ahb_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/orv64_tlb_ptw_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/oursring_resp_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/io_boot_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/vpfp_chkr_wb_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_byp.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_cache.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/acp_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/amo_store_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/vpfp_chkr_id_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/test_io_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/cache_mem_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_sdio.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/cache_fence_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/cpu_cache_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/csr_satp_if.sv
/work/home/yinguohua/Downloads/AMD/orv64/subproj/es1y/rtl_gen/station_test.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/icg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/icg_async.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/icg_rstn.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sync/sync.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sd_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sd_serdes.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sd_sync_fifo.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sd_hold_valid.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_input_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_output_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_ppln_cell_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_ppln_delay_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/ot_4to1_mux_with_buf_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/ot_mux_with_buf_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/ot_one_hot_to_idx.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/arbiter/ot_rr_arbiter_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/arbiter/ot_rr_arbiter_with_hold_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/fifo/sd_flop_fifo_rstn.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/flop_sram.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/flatten_array.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/vcore_gen2/rtl/vcore_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/vcore_gen2/rtl/vcore_ppln_dec_disp.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/vcore_gen2/rtl/vcore_ppln_disp_exe.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/barrel/ot_barrel_shift_left.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/barrel/ot_barrel_shift_right.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sdlib/rtl/verilog/forks/sd_mirror_atomic.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_ppln_cell.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/fifo/sd_flop_fifo.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sdlib/rtl/verilog/closure/sd_input.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/sdlib/rtl/verilog/closure/sd_output.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/misc/sd_id_pool.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/memory/ot_flop_mem_1r1w.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ot_ip/fifo/ot_flop_fifo.v
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_rob.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_fifo.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_vld_rdy_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_one_hot_rr_arb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_vld_rdy_rr_arb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_vld_rdy_rr_arb_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_multi_lyr_vld_rdy_rr_arb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_vld_rdy_delay_line.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_axi4_aw_w_rr_arb_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_axi4_r_rr_arb_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_multi_lyr_axi4_aw_w_rr_arb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_multi_lyr_axi4_r_rr_arb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_conv_oursring_64_to_32.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_input_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_output_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_ip/ours_ppln_cell.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/glitch_free_clk_switch.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/glitch_free_clk_switch_rstn.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/pll.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/clk_div.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/clk_div_pwr2.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/clk_div_cfg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/clock/clk_div_fix.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/inv.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/or_gate.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/clk_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/chip_idle_gen.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/top_cell/mux_Nto1_1bit.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/dft_cell.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_bdg_x2p/ours_bdg_x2p_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_bdg_x2p/ours_bdg_x2p_cvt.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_bdg_x2p/ours_bdg_x2p_fifo.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_bdg_x2p/ours_bdg_x2p_pdec.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_bdg_x2p/ours_bdg_x2p.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_cpu_noc/ours_xm_to_cpu_noc.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_jtag/ours_xm_to_jtag.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_jtag/ours_xm_to_jtag_req_proc.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_jtag/ours_xm_to_jtag_shift_inst_data.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_test_io/ours_xm_to_test_io.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_test_io/ours_xm_to_test_io_req_proc.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/lib/ours_xm_to_test_io/ours_xm_to_test_io_shift_inst_data.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_req_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_req_arbiter.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_req_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_req.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_resp_arbiter.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_resp_ppln.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_resp.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_station.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/oursring/oursring_junction.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_define.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_param_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_typedef_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_func_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_oursring_if_arbiter.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_ram.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_perm_checker.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_napot_addr.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_clk_gating.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_regfile.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_int_regfile.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_fp_regfile.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_fetch.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_decode_func_pkg.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_decode.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_alu.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_mul.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_div.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_execute.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_mem_access.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_edeleg_checker.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_ideleg_checker.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_csr.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_rvc_inst_build.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_icache.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_icache_sysbus.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_inst_buffer.sv                             
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_icache_top.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_storebuf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_dcache_bypass.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_breakpoint.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_stall.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_inst_trace_buf.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_debug_access.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_cache_noc.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_tlb.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_pmp_match.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_pmp_checker.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_ptw_core.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64_ptw.sv
/work/home/yinguohua/Downloads/AMD/orv64/rtl/orv64/orv64.sv
